/*
 * This source file was generated by the Gradle 'init' task
 */
package cicd;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
        App app = new App();
        System.out.println(app.add(4,3));
    }

    public int add(int a, int b) {
        return a + b;
    }
}
